<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'image' => 'rumah_dudukan_speedo_tiger_revo.jpg',
                'name' => 'RUMAH DUDUKAN SPEEDOMETER TIGER REVO - 37212 KCJ 661',
                'price' => 113900,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'cover_bawah_speedo_tiger_revo.jpg',
                'name' => 'COVER BAWAH SPEEDO SPEEDOMETER TIGER REVO - 37110 KCJ 661',
                'price' => 70000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'mika_speedometer_spacy.jpg',
                'name' => 'MIKA SPEEDOMETER SPACY KARBURATOR 2011-2013',
                'price' => 29000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'rumah_dudukan_speedo_megapro.jpg',
                'name' => 'RUMAH DUDUKAN SPEEDOMETER MEGAPRO - 37130 KEH 950',
                'price' => 164000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'speedometer_scoopy.jpg',
                'name' => 'SPEEDOMETER SCOOPY - 37200 KYT 941',
                'price' => 710000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'cover_speedo_megapro.jpg',
                'name' => 'COVER SPEEDOMETER MEGAPRO - 37110 KEH 950',
                'price' => 130000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER FRONT BEAT (KVY) 64301 KVY 960CBO',
                'price' => 480250,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER FRONT BEAT (KVY) 64301 KVY 960ABM',
                'price' => 469000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER FRONT BEAT (KVY) 64301 KVY 960VBM',
                'price' => 428400,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER SAYAP DALAM KANAN SUPRA FIT NEW - 64400 KTL 690DSM',
                'price' => 225000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN TIGER REVO HITAM - 61100 KCJ 660FMB',
                'price' => 255000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'KNALPOT GRAND - 18350 GN5 830',
                'price' => 1300000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN / KIRI REVO 100 - Putih',
                'price' => 136500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN / KIRI REVO 100 - Hitam',
                'price' => 213500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER SAYAP DALAM KIRI SUPRA FIT NEW - Biru',
                'price' => 259000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'LAMPU DEPAN (HEADLIGHT UNIT) SCOOPY KARBURATOR KYT (2010 - 2013)',
                'price' => 209000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER SAYAP DALAM KANAN SUPRA FIT NEW - Silver',
                'price' => 249000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER SAYAP DALAM KIRI SUPRA FIT NEW - Silver',
                'price' => 237500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN REVO 100 - SILVER',
                'price' => 282000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN MEGAPRO LAMA - Silver Hitam Doff',
                'price' => 185000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'LENSA SEIN BELAKANG KIRANAN - 33703 KPW 901',
                'price' => 69000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG DALAM KIRI KHARISMA - Silver',
                'price' => 301500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'LENSA LAMPU STOP BELAKANG KIRANA DAN LENSA SEIN BELAKANG KIRANA (1 SET)',
                'price' => 350000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN / KIRI REVO 100 - Abu',
                'price' => 146500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER BODY BELAKANG KANAN MEGAPRO LAMA BIRU',
                'price' => 160000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER BODY BELAKANG KANAN MEGAPRO LAMA SILVER',
                'price' => 136000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'TAMENG DEPAN / COVER FRONT TOP REVO 100 MERAH',
                'price' => 190000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'TAMENG DEPAN / COVER FRONT TOP REVO 100 HITAM',
                'price' => 170000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'TAMENG DEPAN / COVER FRONT TOP REVO 100 SILVER',
                'price' => 170000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER BODY BELAKANG KANAN KHARISMA X - Hitam',
                'price' => 250000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER BODY BELAKANG KANAN KHARISMA X - Hitam',
                'price' => 250000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN REVO 100 - Merah Bata',
                'price' => 210500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KIRI REVO 100 - Merah Bata',
                'price' => 210500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 125',
                'price' => 207000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 125',
                'price' => 215000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN MEGAPRO MONOSHOCK KARBU (2010)',
                'price' => 230000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER SAYAP DALAM KANAN SUPRA FIT NEW - Dark Grey',
                'price' => 250000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER SAYAP TEBENG KANAN SUPRA X125 BATMAN - Silver',
                'price' => 329000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG DALAM KANAN / KIRI KHARISMA - Biru',
                'price' => 207400,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => '[1 SET] COVER BODY KANAN KIRI DEPAN MEGAPRO LAMA (1999-2004)',
                'price' => 390000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => '[1 SET] COVER BODY KANAN KIRI SUPRA FIT NEW',
                'price' => 330000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN REVO 100 - Biru Muda',
                'price' => 188000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KIRI REVO 100 - Biru Muda',
                'price' => 188000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN REVO 100 - Merah Tua',
                'price' => 264000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KIRI REVO 100 - Merah Tua',
                'price' => 264000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Biru Muda',
                'price' => 147500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Orange',
                'price' => 195000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Hitam',
                'price' => 165000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Putih',
                'price' => 156000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Ungu',
                'price' => 135000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR BELAKANG ASTREA STAR PRIMA',
                'price' => 500000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER SAYAP DALAM KANAN / KIRI SUPRA FIT NEW - Coklat Metalic',
                'price' => 331800,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => '[1 SET] COVER BODY KANAN KIRI DEPAN GL PRO / GL MAX (1985)',
                'price' => 360000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG SAYAP DALAM KIRI REVO 100 - Silver',
                'price' => 189000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'GASKET CYLINDER CBR150R STREETFIRE (2012-2015) & CBR 150R K54A (2014-2016)',
                'price' => 11000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG SAYAP LUAR KANAN KHARISMA - Blue',
                'price' => 175000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG SAYAP LUAR KIRI KHARISMA - Blue',
                'price' => 175000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'KNALPOT SUPRA FIT - 18350 KRS A00',
                'price' => 800000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN MEGAPRO PRIMUS (2006-2009)',
                'price' => 235000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 110 CW (2006 - 2014) Hitam',
                'price' => 175000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 110 CW (2006 - 2014) Merah',
                'price' => 136500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 110 CW (2006 - 2014) Biru',
                'price' => 165000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 110 CW (2006 - 2014) Putih',
                'price' => 156000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER BODY BELAKANG KIRI KHARISMA X - Silver',
                'price' => 216900,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG DALAM KIRI KHARISMA - Merah',
                'price' => 295800,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN KIRANA - Hitam',
                'price' => 375000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN KIRANA - Silver',
                'price' => 475000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG SAYAP LUAR KANAN KHARISMA - Hitam',
                'price' => 199900,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG SAYAP LUAR KIRI KHARISMA - Hitam',
                'price' => 199900,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KIRI SUPRA X125 BATMAN - Hitam Glitter Ungu',
                'price' => 335000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN CS1 (2008 - 2013)',
                'price' => 140000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN CS1 - DARK GREY SILVER MATTE',
                'price' => 194000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 720 (2008-2012) Ungu Muda',
                'price' => 155000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 720 (2008-2012) Hijau',
                'price' => 175000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 720 (2008-2012) Biru',
                'price' => 190000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'GASKET CYLINDER HEAD CBR150R STREETFIRE K15 (2012-2015)',
                'price' => 28500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'SPAKBOR SLEBOR DEPAN GL PRO / GL MAX (1985)',
                'price' => 310000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => '[1 SET] COVER BODY KANAN KIRI DEPAN TIGER 2000 (1993 - 2006)',
                'price' => 460000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN / KIRI REVO 100 - Biru',
                'price' => 215500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN REVO 100 - Kuning',
                'price' => 128000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KIRI REVO 100 - Kuning',
                'price' => 128000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN REVO 100 - Orange',
                'price' => 134500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KIRI REVO 100 - Orange',
                'price' => 134500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KANAN REVO 100 - Merah',
                'price' => 140500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER TEBENG KIRI REVO 100 - Merah',
                'price' => 140500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER BODY BELAKANG KIRI MEGAPRO LAMA - Silver',
                'price' => 181800,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER BODY BELAKANG KIRI MEGAPRO LAMA - Merah',
                'price' => 171100,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER FRONT / COVER BODY DEPAN VARIO 110 CW (2006 - 2014) - ABM',
                'price' => 495000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER FRONT / COVER BODY DEPAN VARIO 110 CW (2006 - 2014) - JBM',
                'price' => 573000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER FRONT / COVER BODY DEPAN VARIO 110 CW (2006 - 2014) - PPM',
                'price' => 375000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '',
                'name' => 'COVER FRONT / COVER BODY DEPAN VARIO 110 CW (2006 - 2014) - WR',
                'price' => 459000,
                'type' => 'SUKU CADANG MOTOR',
            ],
        ]);
    }
}
