<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'image' => 'rumah_dudukan_speedo_tiger_revo.png',
                'name' => 'RUMAH DUDUKAN SPEEDOMETER TIGER REVO - 37212 KCJ 661',
                'price' => 113900,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'cover_bawah_speedo_tiger_revo.png',
                'name' => 'COVER BAWAH SPEEDO SPEEDOMETER TIGER REVO - 37110 KCJ 661',
                'price' => 70000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'mika_speedometer_spacy.png',
                'name' => 'MIKA SPEEDOMETER SPACY KARBURATOR 2011-2013',
                'price' => 29000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'rumah_dudukan_speedo_megapro.png',
                'name' => 'RUMAH DUDUKAN SPEEDOMETER MEGAPRO - 37130 KEH 950',
                'price' => 164000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'speedometer_scoopy.png',
                'name' => 'SPEEDOMETER SCOOPY - 37200 KYT 941',
                'price' => 710000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'cover_speedo_megapro.png',
                'name' => 'COVER SPEEDOMETER MEGAPRO - 37110 KEH 950',
                'price' => 130000,
                'type' => 'AKSESORIS MOTOR',
            ],
            [
                'image' => 'cover_front_beat_960CBO.png',
                'name' => 'COVER FRONT BEAT (KVY) 64301 KVY 960CBO',
                'price' => 480250,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_front_beat_960ABM.png',
                'name' => 'COVER FRONT BEAT (KVY) 64301 KVY 960ABM',
                'price' => 469000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_front_beat_960VBM.png',
                'name' => 'COVER FRONT BEAT (KVY) 64301 KVY 960VBM',
                'price' => 428400,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_sayap_dalam_kanan_supra_fit.png',
                'name' => 'COVER SAYAP DALAM KANAN SUPRA FIT NEW - 64400 KTL 690DSM',
                'price' => 225000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_tiger_revo.png',
                'name' => 'SPAKBOR SLEBOR DEPAN TIGER REVO HITAM - 61100 KCJ 660FMB',
                'price' => 255000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'knalpot_grand_18350.png',
                'name' => 'KNALPOT GRAND - 18350 GN5 830',
                'price' => 1300000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_kiri_revo_putih.png',
                'name' => 'COVER TEBENG KANAN / KIRI REVO 100 - Putih',
                'price' => 136500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_kiri_revo_hitam.png',
                'name' => 'COVER TEBENG KANAN / KIRI REVO 100 - Hitam',
                'price' => 213500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_sayap_dalam_kanan_supra_fit_biru.png',
                'name' => 'COVER SAYAP DALAM KIRI SUPRA FIT NEW - Biru',
                'price' => 259000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'lampu_depan_scoopy_karburator_kyt.png',
                'name' => 'LAMPU DEPAN (HEADLIGHT UNIT) SCOOPY KARBURATOR KYT (2010 - 2013)',
                'price' => 209000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_sayap_dalam_kanan_supra_fit_silver.png',
                'name' => 'COVER SAYAP DALAM KANAN SUPRA FIT NEW - Silver',
                'price' => 249000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_sayap_dalam_kiri_supra_fit_silver.png',
                'name' => 'COVER SAYAP DALAM KIRI SUPRA FIT NEW - Silver',
                'price' => 237500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_revo_100_silver.png',
                'name' => 'SPAKBOR SLEBOR DEPAN REVO 100 - SILVER',
                'price' => 282000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_megapro_lama_silver_hitam_doff.png',
                'name' => 'SPAKBOR SLEBOR DEPAN MEGAPRO LAMA - Silver Hitam Doff',
                'price' => 185000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'lensa_sein_belakang_kiranan.png',
                'name' => 'LENSA SEIN BELAKANG KIRANAN - 33703 KPW 901',
                'price' => 69000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_dalam_kiri_kharisma_silver.png',
                'name' => 'COVER TEBENG DALAM KIRI KHARISMA - Silver',
                'price' => 301500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'lensa_stop_belakang_kirana.png',
                'name' => 'LENSA LAMPU STOP BELAKANG KIRANA DAN LENSA SEIN BELAKANG KIRANA (1 SET)',
                'price' => 350000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_kiri_revo_100_abu.png',
                'name' => 'COVER TEBENG KANAN / KIRI REVO 100 - Abu',
                'price' => 146500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_body_belakang_kiri_megapro_lama_biru.png',
                'name' => 'COVER BODY BELAKANG KANAN MEGAPRO LAMA BIRU',
                'price' => 160000,
                'type' => 'SUKU CADANG MOTOR',
            ],

            //siin
            [
                'image' => 'cover_body_belakang_kanan_megapro_lama_silver.png',
                'name' => 'COVER BODY BELAKANG KANAN MEGAPRO LAMA SILVER',
                'price' => 136000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'tameng_depan_revo_100_merah.png',
                'name' => 'TAMENG DEPAN / COVER FRONT TOP REVO 100 MERAH',
                'price' => 190000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'tameng_depan_revo_100_hitam.png',
                'name' => 'TAMENG DEPAN / COVER FRONT TOP REVO 100 HITAM',
                'price' => 170000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'tameng_depan_revo_100_silver.png',
                'name' => 'TAMENG DEPAN / COVER FRONT TOP REVO 100 SILVER',
                'price' => 170000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_body_belakang_kiri_kharisma_x_hitam.png',
                'name' => 'COVER BODY BELAKANG KANAN KHARISMA X - Hitam',
                'price' => 250000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_body_belakang_kanan_kharisma_x_hitam.png',
                'name' => 'COVER BODY BELAKANG KANAN KHARISMA X - Hitam',
                'price' => 250000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_revo_100_merah_bata.png',
                'name' => 'COVER TEBENG KANAN REVO 100 - Merah Bata',
                'price' => 210500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kiri_revo_100_merah_bata.png',
                'name' => 'COVER TEBENG KIRI REVO 100 - Merah Bata',
                'price' => 210500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_vario_125_orange.png',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 125',
                'price' => 207000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_vario_125_putih.png',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 125',
                'price' => 215000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_megapro_2010.png',
                'name' => 'SPAKBOR SLEBOR DEPAN MEGAPRO MONOSHOCK KARBU (2010)',
                'price' => 230000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_sayap_dalam_kanan_supra_fit_new_dark_grey.png',
                'name' => 'COVER SAYAP DALAM KANAN SUPRA FIT NEW - Dark Grey',
                'price' => 250000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_sayap_tebeng_kanan_supra_x125_batman.png',
                'name' => 'COVER SAYAP TEBENG KANAN SUPRA X125 BATMAN - Silver',
                'price' => 329000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_dalam_kanan_kharisma_biru.png',
                'name' => 'COVER TEBENG DALAM KANAN / KIRI KHARISMA - Biru',
                'price' => 207400,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '1_set_cover_body_kanan_kiri_depan_megapro_lama.png',
                'name' => '[1 SET] COVER BODY KANAN KIRI DEPAN MEGAPRO LAMA (1999-2004)',
                'price' => 390000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '1_set_cover_body_kanan_kiri_supra_fit_new.png',
                'name' => '[1 SET] COVER BODY KANAN KIRI SUPRA FIT NEW',
                'price' => 330000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_revo_100_biru_muda.png',
                'name' => 'COVER TEBENG KANAN REVO 100 - Biru Muda',
                'price' => 188000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kiri_revo_100_biru_muda.png',
                'name' => 'COVER TEBENG KIRI REVO 100 - Biru Muda',
                'price' => 188000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_revo_100_merah_tua.png',
                'name' => 'COVER TEBENG KANAN REVO 100 - Merah Tua',
                'price' => 264000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kiri_revo_100_merah_tua.png',
                'name' => 'COVER TEBENG KIRI REVO 100 - Merah Tua',
                'price' => 264000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_beat_karburator_kvy_930_biru_muda.png',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Biru Muda',
                'price' => 147500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_beat_karburator_kvy_930_orange.png',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Orange',
                'price' => 195000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_beat_karburator_kvy_930_hitam.png',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Hitam',
                'price' => 165000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_beat_karburator_kvy_930_putih.png',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Putih',
                'price' => 156000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_beat_karburator_kvy_930_ungu.png',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 930 (2008-2012) - Ungu',
                'price' => 135000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_belakang_astrea_star_prima.png',
                'name' => 'SPAKBOR BELAKANG ASTREA STAR PRIMA',
                'price' => 500000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_sayap_dalam_kanan_kiri_supra_fit_new_coklat.png',
                'name' => 'COVER SAYAP DALAM KANAN / KIRI SUPRA FIT NEW - Coklat Metalic',
                'price' => 331800,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '1_set_cover_body_kanan_kiri_depan_gl_pro_gl_max.png',
                'name' => '[1 SET] COVER BODY KANAN KIRI DEPAN GL PRO / GL MAX (1985)',
                'price' => 360000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_sayap_dalam_kanan_revo_100_silver.png',
                'name' => 'COVER TEBENG SAYAP DALAM KIRI REVO 100 - Silver',
                'price' => 189000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'gasket_cylinder_cbr150r_streetfire.png',
                'name' => 'GASKET CYLINDER CBR150R STREETFIRE (2012-2015) & CBR 150R K54A (2014-2016)',
                'price' => 11000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' =>'cover_tebeng_sayap_luar_kanan_kharisma_biru.png',
                'name' => 'COVER TEBENG SAYAP LUAR KANAN KHARISMA - Blue',
                'price' => 175000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_sayap_luar_kiri_kharisma_biru.png',
                'name' => 'COVER TEBENG SAYAP LUAR KIRI KHARISMA - Blue',
                'price' => 175000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'knalpot_supra_fit_18350.png',
                'name' => 'KNALPOT SUPRA FIT - 18350 KRS A00',
                'price' => 800000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_megapro_primus.png',
                'name' => 'SPAKBOR SLEBOR DEPAN MEGAPRO PRIMUS (2006-2009)',
                'price' => 235000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_vario_110_cw_hitam.png',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 110 CW (2006 - 2014) Hitam',
                'price' => 175000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_vario_110_cw_merah.png',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 110 CW (2006 - 2014) Merah',
                'price' => 136500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_vario_110_cw_biru.png',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 110 CW (2006 - 2014) Biru',
                'price' => 165000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_vario_110_cw_putih.png',
                'name' => 'SPAKBOR SLEBOR DEPAN VARIO 110 CW (2006 - 2014) Putih',
                'price' => 156000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_body_belakang_kiri_kharisma_x_silver.png',
                'name' => 'COVER BODY BELAKANG KIRI KHARISMA X - Silver',
                'price' => 216900,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_body_dalam_kiri_kharisma_merah.png',
                'name' => 'COVER TEBENG DALAM KIRI KHARISMA - Merah',
                'price' => 295800,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_kirana_hitam.png',
                'name' => 'SPAKBOR SLEBOR DEPAN KIRANA - Hitam',
                'price' => 375000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_kirana_silver.png',
                'name' => 'SPAKBOR SLEBOR DEPAN KIRANA - Silver',
                'price' => 475000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_sayap_luar_kanan_kharisma_hitam.png',
                'name' => 'COVER TEBENG SAYAP LUAR KANAN KHARISMA - Hitam',
                'price' => 199900,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_sayap_luar_kiri_kharisma_hitam.png',
                'name' => 'COVER TEBENG SAYAP LUAR KIRI KHARISMA - Hitam',
                'price' => 199900,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kiri_supra_x125_batman_hitam_glitter_ungu.png',
                'name' => 'COVER TEBENG KIRI SUPRA X125 BATMAN - Hitam Glitter Ungu',
                'price' => 335000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_cs1.png',
                'name' => 'SPAKBOR SLEBOR DEPAN CS1 (2008 - 2013)',
                'price' => 140000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_cs1_dark_grey_silver.png',
                'name' => 'SPAKBOR SLEBOR DEPAN CS1 - DARK GREY SILVER MATTE',
                'price' => 194000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_beat_karburator_kvy_720_ungu_muda.png',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 720 (2008-2012) Ungu Muda',
                'price' => 155000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_beat_karburator_kvy_720_hijau.png',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 720 (2008-2012) Hijau',
                'price' => 175000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_beat_karburator_kvy_720_biru.png',
                'name' => 'SPAKBOR SLEBOR DEPAN BEAT KARBURATOR KVY 720 (2008-2012) Biru',
                'price' => 190000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'gasket_cylinder_head_cbr150r_streetfire_k15.png',
                'name' => 'GASKET CYLINDER HEAD CBR150R STREETFIRE K15 (2012-2015)',
                'price' => 28500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'spakbor_slebor_depan_gl_pro_gl_max.png',
                'name' => 'SPAKBOR SLEBOR DEPAN GL PRO / GL MAX (1985)',
                'price' => 310000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => '1_set_cover_body_kanan_kiri_depan_tiger_2000.png',
                'name' => '[1 SET] COVER BODY KANAN KIRI DEPAN TIGER 2000 (1993 - 2006)',
                'price' => 460000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_revo_100_biru.png',
                'name' => 'COVER TEBENG KANAN / KIRI REVO 100 - Biru',
                'price' => 215500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_revo_100_kuning.png',
                'name' => 'COVER TEBENG KANAN REVO 100 - Kuning',
                'price' => 128000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kiri_revo_100_kuning.png',
                'name' => 'COVER TEBENG KIRI REVO 100 - Kuning',
                'price' => 128000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_revo_100_orange.png',
                'name' => 'COVER TEBENG KANAN REVO 100 - Orange',
                'price' => 134500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kiri_revo_100_orange.png',
                'name' => 'COVER TEBENG KIRI REVO 100 - Orange',
                'price' => 134500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kanan_revo_100_merah.png',
                'name' => 'COVER TEBENG KANAN REVO 100 - Merah',
                'price' => 140500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_tebeng_kiri_revo_100_merah.png',
                'name' => 'COVER TEBENG KIRI REVO 100 - Merah',
                'price' => 140500,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_body_belakang_kiri_megapro_lama_silver.png',
                'name' => 'COVER BODY BELAKANG KIRI MEGAPRO LAMA - Silver',
                'price' => 181800,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_body_belakang_kiri_megapro_lama_merah.png',
                'name' => 'COVER BODY BELAKANG KIRI MEGAPRO LAMA - Merah',
                'price' => 171100,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_front_cover_body_depan_vario_110_cw_amb.png',
                'name' => 'COVER FRONT / COVER BODY DEPAN VARIO 110 CW (2006 - 2014) - ABM',
                'price' => 495000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_front_cover_body_depan_vario_110_cw_jbm.png',
                'name' => 'COVER FRONT / COVER BODY DEPAN VARIO 110 CW (2006 - 2014) - JBM',
                'price' => 573000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_front_cover_body_depan_vario_110_cw_ppm.png',
                'name' => 'COVER FRONT / COVER BODY DEPAN VARIO 110 CW (2006 - 2014) - PPM',
                'price' => 375000,
                'type' => 'SUKU CADANG MOTOR',
            ],
            [
                'image' => 'cover_front_cover_body_depan_vario_110_cw_wr.png',
                'name' => 'COVER FRONT / COVER BODY DEPAN VARIO 110 CW (2006 - 2014) - WR',
                'price' => 459000,
                'type' => 'SUKU CADANG MOTOR',
            ],
        ]);
    }
}
